### ISSUE TITLE
Manufactures ID

### ISSUE THREAD

**Issue by johnmholmes** [cbus-traincontrol/cbus-traincontrol.github.io#4]
Gents would it be possible to have an ID for MERG Arduino developers

**Comment by pnbgit** [comment]
Hello  John. Module type ids are defined in cbusdefs, so better to ask that querstion there, you're more likeliy to get a response.  As per the forum disucssions, module type ids are not specifc to any particular processor type, they relate to the module funcitonality itself. For development purposes, there is now module type id 99, which is "Module under development". You can use that type id for any new module you are developing, regardless of processor. That id is defined in cbusdefs version 8y.  At the time of writing that version is not yet released, but you can reference version 8y (WIP) by using the verson 8y branch in the cbusderfs respository. If/when you get to a pont where you are sharing the software for a particular module functionality with others, that is the time to request a specific module type id for that dnew module. You can do that either via the cbusdefs repository, or via the MERG forum, or by email to me. I am currently looking after CBUS module definition codes, which I took over from Roger Healey when he stepped back from that role.    Pete.

**Comment by johnmholmes** [comment]
Thank you for the explanation I am closing this as I am aware there is a planned release in the future to make this readily available.
